### ISSUE TITLE
Calculate usage of IPA sites

### ISSUE THREAD

**Issue by cloudyrainy-zh** [YY-TMU/InPACT#6] opened 2024-05-03 06:27 UTC
In the third step, InPACT_quantify is running with the following error, and I would like to know which file is at fault

 Traceback (most recent call last):
  File "/home/data/miniconda3/envs/InPACT/bin/InPACT_quantify", line 103, in <module>
    ipa_usage_dic = calculate_usage(transcript_tpm_path,
  File "/home/data/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in calculate_usage
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
  File "/home/data/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in <listcomp>
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
KeyError: 'NM_000350.3'

Thank you very much.

**Comment by liuxc1995** [comment] 2024-05-05 00:42
Hello! Thank you for your question.

For successful execution of the `InPACT_quantify` step, several key files are indispensable:

1. **predict.result.txt**: This file is generated through the execution of `InPACT` command.
2. **merged.gtf**: This file is derived from the `InPACT_transcript` command.
3. **quant.sf**: Produced by `Salmon`, this file is essential for downstream analyses. It is important to note that the index for the transcriptome used in `Salmon` should be constructed based on the **merged.gtf** file.

To ensure the smooth execution of the `InPACT_quantify` command, it is recommended to meticulously verify the integrity and compatibility of these input files.

Thank you,
Liu

**Comment by Badman1025** [comment] 2024-09-04 14:30
Hello, I encountered the same issue. The first step outputted a file named predict.result.txt, and the second step generated a merged.gtf. I believe these two steps should be correct, but I also encountered an error in the third step:

Traceback (most recent call last):
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 103, in <module>
    ipa_usage_dic = calculate_usage(transcript_tpm_path,
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in calculate_usage
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in <listcomp>
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
KeyError: 'NM_001080438.1'
Even though the quant.sf file may output different names due to the fa file:
hg38.fa：
Name	Length	EffectiveLength	TPM	NumReads
chr1	248956422	248956133.387	66.538852	2386248.779
chr10	133797422	133797133.387	43.224727	833099.075
chr11	135086622	135086333.387	73.907179	1438187.886
chr11_KI270721v1_random	100316	100027.387	0.000000	0.000
chr12	133275309	133275020.387	59.799460	1148057.411
Homo_sapiens.GRCh38.cdna.all.fa：
Name	Length	EffectiveLength	TPM	NumReads
ENST00000631435.1	12	12.000	0.000000	0.000
ENST00000415118.1	8	8.000	0.000000	0.000
ENST00000448914.1	13	13.000	0.000000	0.000
ENST00000434970.2	9	9.000	0.000000	0.000
others：

**Comment by liuxc1995** [comment] 2024-09-05 01:27
The error likely stems from an issue during the Salmon run. To resolve it, follow these steps:

First, ensure you have a set of target transcripts for quantification. Extract the transcript sequences from the `merged.gtf` file using gffread.
`gffread merged.gtf -g <genome.fa> -w transcripts.fa`

Next, build the transcriptome index with Salmon.
`salmon index -t trasncripts.fa -i <index> -k 31`

After building the index, you can quantify against this index using Salmon for accurate quantification.

I think this process should help avoid errors.

**Comment by Badman1025** [comment] 2024-09-05 02:14
In the response mentioned at https://github.com/YY-TMU/InPACT/issues/10, I used the hg38.fa file. I attempted the step with the command "gffread merged.gtf -g hg38.fa -w transcripts.fa", during which the following error occurred:

Warning: couldn't find fasta record for 'chr10_KN196480v1_fix'!
Error: no genomic sequence available (check -g option!).
Despite the error, I reviewed the output results. Here is the head of the transcripts.fa file:

>NM_001005484.2 CDS=61-1041
CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGTAGTCTCTTCCAGTTATGAAGAAGG
TAACTGCAGAGGCTATTTCCTGGAATGAATCAACGAGTGAAACGAATAACTCTATGGTGACTGAATTCAT
...
I decided to use this erroneous result to try subsequent operations and build the index. Here is the head of the quant.sf file:

Name	Length	EffectiveLength	TPM	NumReads
NM_001005484.2	2618	2326.487	0.000000	0.000
NM_001005221.2	939	647.817	0.000000	0.000
...
The name format of the other transcript output results is consistent:

Name Length EffectiveLength TPM NumReads
NM_001080438.1 248956422 248956133.3 66.538614 2386248.409
NM_001080438.1 133797422 133797133.3 43.224636 833100.172
NM_001080438.1 135086622 135086333.3 73.906931 1438187.977
The result is still the same error:

Traceback (most recent call last):
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 103, in <module>
    ipa_usage_dic = calculate_usage(transcript_tpm_path,
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in calculate_usage
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
  File "/root/miniconda3/envs/InPACT/bin/InPACT_quantify", line 48, in <listcomp>
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
KeyError: 'NM_012199.5'
Finally, please upload the final ipa_usage.txt format for reference.

Thank you.

**Comment by liuxc1995** [comment] 2024-09-05 02:44
We were unable to reproduce the error with gffread on our end. I recommend trying the command with different annotation files to verify the command. If the problem persists, feel free to send your complete code and files to my email (liuxc1995@tmu.edu.cn), and we’ll be happy to assist with troubleshooting. And the final ipa_usage.txt format is in README part.

**Closed** 2024-11-20 10:36 UTC

**Comment by abr5988** [comment] 2025-01-24 17:00
I have also encountered the same exact error above, despite following all suggested steps to my knowledge. It is even producing an error with the same transcript name as above^.

**Here is my full code:**

Define directory
`proj_dir=/path/to/directory` 

Step 1. Identify IPA sites
`InPACT -i input.bam -a ${proj_dir}/hg38.109.20211119.ncbiRefSeq.gtf -s ${proj_dir}/InPACT/annos/InPACT_polyAsites.hg38.saf -P 5 --save_dir ${proj_dir}` 

Step 2. Infer novel transcripts
`InPACT_transcript --predict_terminal ${proj_dir}/1.predicted.terminal.results.txt --annotated_gtf ${proj_dir}/hg38.109.20211119.ncbiRefSeq.gtf --fa_path ${proj_dir}/hg38.fa --save_gtf ${proj_dir}/merged.gtf`

Salmon
Extract the sequence of transcripts using gffread
`gffread ${proj_dir}/merged.gtf -g ${proj_dir}/hg38.fa -w ${proj_dir}/hg38_transcripts.fa`

Build index
`salmon index -t ${proj_dir}/hg38_transcripts.fa -i ${proj_dir}/transcripts_index -k 31`

For paired-end reads, pass them to Salmon with the -r flag like:
`salmon quant -i ${proj_dir}/transcripts_index -l A -1 ${proj_dir}/input_R1.fq.gz -2 ${proj_dir}/input_R2.fq.gz --validateMappings -o ${proj_dir}/transcripts_quant` # chose automatic libtype

Step 3. Calculate IPA site usage
`InPACT_quantify --transcript_tpm ${proj_dir}/transcripts_quant/quant.sf --annotation_file ${proj_dir}/merged.gtf --ipa_info ${proj_dir}/1.predicted.terminal.results.txt --save_file ${proj_dir}/ipa_usage.txt`

**And here is the error message:** 

######################### Start : IPA Usage #########################
Traceback (most recent call last):
  File "/home/abr5988/.conda/envs/InPACT/bin/InPACT_quantify", line 103, in <module>
    ipa_usage_dic = calculate_usage(transcript_tpm_path,
  File "/home/abr5988/.conda/envs/InPACT/bin/InPACT_quantify", line 48, in calculate_usage
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
  File "/home/abr5988/.conda/envs/InPACT/bin/InPACT_quantify", line 48, in <listcomp>
    gene_tpm_dic[gn] = sum([transcript_tpm_dic[transcript] for transcript in transcripts])
KeyError: 'NM_012199.5'

Please let me know if there is anything I should fix in the above code. I used the NCBI Refseq GTF file linked in the description as well as the provided InPACT_polyAsites.hg38.saf. Thank you!
